name: MiniBoard Build with Maven

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload MiniBoard
      uses: actions/upload-artifact@v2.2.3
      with:
        name: MiniBoard-JDK11
        path: target/MiniBoard.jar
